using Microsoft.EntityFrameworkCore.Metadata.Builders;

using System.Linq.Expressions;

namespace Firebrand.Data.Extensions;

public static class EntityTypeBuilderExtensions
{
    public static void AutoGeneratedIdentity<TEntity>(this EntityTypeBuilder<TEntity> builder, Expression<Func<TEntity, object?>> keyExpression) where TEntity : class
    {
        builder.HasKey(keyExpression);
        builder.Property(keyExpression)
            .ValueGeneratedOnAdd();
    }
}